service: goo-thesis-math
# Configuracion del proveedor
provider:
  name: google
  runtime: python37
  region: us-central1
  project: tesis-gcl
  memorySize: 2048
  timeout: 540s
  credentials: ../../keyfile.json
# Plugin para despliegue
plugins:
  - serverless-google-cloudfunctions
# Creaci贸n de paquete de implementaci贸m
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - "*.json"
# Configuraci贸n de funci贸n
functions:
  # nombre
  fft:
    # punto de entrada
    handler: math
    # desencadenador
    events:
      - http: path


