service: goo-thesis-ml
provider:
  name: google
  runtime: python37
  region: us-central1
  project: tesis-gcl
  memorySize: 2048
  timeout: 540s
  credentials: ../../keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - package.json
    - package-lock.json

functions:
  ml:
    handler: ml
    events:
      - http: path
